# Generated by Django 4.2.8 on 2026-01-11 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('INICIO_INTERVALO', 'Início do Intervalo'), ('FIM_INTERVALO', 'Fim do Intervalo'), ('SAIDA', 'Saída')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'hora'],
                'indexes': [models.Index(fields=['user', 'data'], name='timerecords_user_id_c73375_idx')],
                'unique_together': {('user', 'data', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('AUSENTE', 'Ausente'), ('INCONSISTENTE', 'Inconsistente')], default='AUSENTE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
